client:
  serverHost: localhost
  serverPort: 8867
  password: 123123
  proxies:
    - host: localhost
      port: 4456
      protocol: tcp
      open-port: 8890
#    - host: localhost
#      port: 4457
#      protocol: udp
#      open-port: 8891




server:
  port: 8876
